# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main, master ]  # Deploy on push to main/master
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/amize
          git pull origin main
          npm install
          npx prisma migrate deploy
          npx prisma generate
          npm run build
          pm2 restart amize || pm2 start npm --name "amize" -- start
          pm2 save
